### ISSUE TITLE
[0.16.5] [LOW_MEM] webserver-http-endpoint broken

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#418]
While using LOW_MEM node, unable to connect to `webserver-http-endpoint`:

config.ini:
```
webserver-http-endpoint = 0.0.0.0:8090
```

Port 8090 is mapped to host 9090 port:

```
version: "2.2"
services:
  testnet:
    image: golos-0.16.5-testnet-lowmem
    ports:
      - "3001:2001"
      - "9090:8090"
      - "9091:8091"
    volumes:
      - "./share/golosd/config/config_debug.ini:/etc/golosd/config.ini"
```

```
% telnet localhost 9090
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
